site_name: FOM.tft-timeseries – Notizen
site_description: Projektdokumentation, Dev Notes und Konfiguration
theme:
  name: material
  language: de
  features:
    - navigation.instant
    - navigation.sections
    - content.code.copy
    - content.tabs.link
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - attr_list

nav:
  - Übersicht: index.md
  - Projekt Pipeline:
      - Pipeline Übersicht: shared/PipelineOrder.md
      - Pipeline Script: project/Pipeline.md
  - Projekt Schritte:
      - Data Preprocessing:
        - Load Data: projct/LoadRaw.md
        - Data Alignment: project/DataAlignment.md
        - Data Cleaning: project/DataCleaning.md
        - Data Cleaning Plot: project/DataCleaningPlot.md
        - Feature Engineering: project/FeatureEngineer.md
        - Cyclical Encoder: project/CyclicalEncoder.md
        - Lag Features: project/LagFeatures.md
      - Modeling:
        - Model Dataset: project/ModelDataset.md
        - Dataset TFT: project/DatasetTFT.md
        - Trainer TFT: project/TrainerTFT.md
      - Evaluation:
        - Evaluation TFT: project/EvaluatorTFT.md
        - Evaluation TFT Plot: project/EvaluatorTFTPlot.md
  - Hyperparameter Optimierung:
      - Optuna: project/Optuna.md
  - Allgemeine Dokumentation:
      - Projektstruktur: shared/Projektstruktur.md
      - Projekt Arbeitsweise: shared/ProjektArbeitsweise.md
      - Configs & Setup: shared/ConfigSetup.md
      - Trainer & Evaluator Struktur: shared/TrainerEvaluator_Stuktur.md
      - MkDocs Nutzung: shared/MkDocsUsage.md
  - Geplant:
      - ARIMA und Prophet: shared/ArimaProphetIntegration.md
      - Integration in MLFlow: shared/MLFlowKonzept.md