type: arima
name: optuna_best_trial3
description: Beste Config aus Optuna Study 'arima_booksales' (Trial 3, val_mae=23.6223)
model:
  auto_arima: true
  max_p: 4
  max_d: 1
  max_q: 1
  max_P: 0
  max_D: 1
  max_Q: 0
  start_p: 0
  start_q: 0
  start_P: 0
  start_Q: 0
  seasonal: true
  m: 7
  stepwise: true
  suppress_warnings: true
  error_action: ignore
  trace: false
training:
  prediction_length: 7
optuna_metadata:
  study_name: arima_booksales
  trial_number: 3
  val_mae: 23.62225361364357
  all_params:
    max_p: 4
    max_q: 1
    max_P: 0
    max_Q: 0
