type: tft
name: trial15
description: 'Trial 15 aus Optuna Study ''tft_day'' (State: COMPLETE, val_mae=9.892058372497559)'
training:
  seed: 42
  max_epochs: 50 # vorher: 30
  batch_size: 64
  learning_rate: 0.001454205767800031
  gradient_clip_val: 0.100256976761273
  early_stopping_patience: 10 # vorher: 5
  accelerator: gpu
  devices: 1
  num_workers: 4
  limit_train_batches: 1.0
  limit_val_batches: 1.0
model:
  loss: quantile
  output_size: 7
  hidden_size: 64
  attention_head_size: 3
  hidden_continuous_size: 24
  dropout: 0.07679602499392002
  reduce_on_plateau_patience: 2
evaluation:
  batch_size: 256
  num_workers: 0
optuna_metadata:
  study_name: tft_day
  trial_number: 15
  trial_state: COMPLETE
  val_mae: 9.892058372497559
  all_params:
    learning_rate: 0.001454205767800031
    batch_size: 64
    hidden_size: 64
    attention_head_size: 3
    dropout: 0.07679602499392002
    hidden_continuous_size: 24
    gradient_clip_val: 0.100256976761273
